# Generated by Django 5.2 on 2025-04-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextosJuridicosTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teor_texto', models.TextField()),
                ('assuntos', models.CharField(blank=True, max_length=255, null=True)),
                ('classe_processo', models.CharField(blank=True, max_length=100, null=True)),
                ('orgao_julgador', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
