# Generated by Django 5.2 on 2025-04-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textosjuridicostreinamento',
            name='setor_destino',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
