# Generated by Django 5.2 on 2025-04-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_textosjuridicostreinamento_setor_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='textosjuridicostreinamento',
            name='demanda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textosjuridicostreinamento',
            name='setor_destino_validated',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='textosjuridicostreinamento',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
