# Generated by Django 5.2 on 2025-04-15 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegraClassificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('demanda', models.TextField(blank=True, null=True)),
                ('prioridade', models.IntegerField(default=0)),
                ('setor_destino', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoCondicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')])),
                ('grupo_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subgrupos', to='rules.grupocondicao')),
                ('regras', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='rules.regraclassificacao')),
            ],
        ),
        migrations.CreateModel(
            name='Condicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('teor_texto', 'Teor do Texto'), ('classe_processo', 'Classe do Processo'), ('assuntos', 'Assuntos'), ('orgao_julgador', 'Orgão Julgador')], max_length=50)),
                ('operador', models.CharField(choices=[('CONTAINS', 'Contém'), ('EQUALS', 'Igual a')], max_length=20)),
                ('valor', models.TextField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condicoes', to='rules.grupocondicao')),
            ],
        ),
    ]
