# Generated by Django 5.2 on 2025-04-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupocondicao',
            old_name='regras',
            new_name='regra',
        ),
    ]
