# Generated by Django 5.2 on 2025-04-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_rename_regras_grupocondicao_regra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupocondicao',
            name='grupo_pai',
        ),
        migrations.RemoveField(
            model_name='grupocondicao',
            name='regra',
        ),
        migrations.AddField(
            model_name='regraclassificacao',
            name='expressao',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Condicao',
        ),
        migrations.DeleteModel(
            name='GrupoCondicao',
        ),
    ]
